services:
  - type: web
    name: pgadmin
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@admin.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin
